const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {

    const prompt = `You are an expert interview coach. Analyze the candidate profile against the job description and return ONLY a valid JSON object. No markdown, no explanation, just raw JSON.

Job Description: ${jobDescription}
Resume: ${resume}
Self Description: ${selfDescription}

Return exactly this JSON structure:
{
  "title": "job title from the job description",
  "matchScore": 75,
  "technicalQuestions": [
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" }
  ],
  "behavioralQuestions": [
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" },
    { "question": "question text", "intention": "why this is asked", "answer": "how to answer it" }
  ],
  "skillGaps": [
    { "skill": "skill name", "severity": "high" },
    { "skill": "skill name", "severity": "medium" },
    { "skill": "skill name", "severity": "low" }
  ],
  "preparationPlan": [
    { "day": 1, "focus": "focus area", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 2, "focus": "focus area", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 3, "focus": "focus area", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 4, "focus": "focus area", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 5, "focus": "focus area", "tasks": ["task 1", "task 2", "task 3"] }
  ]
}`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
        }
    })

    return JSON.parse(response.text)
}

// ✅ moved above generateResumePdf
async function generatePdfFromHtml(htmlContent) {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setContent(htmlContent, { waitUntil: "networkidle0" })

    const pdfBuffer = await page.pdf({
        format: "A4",
        margin: {
            top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
        }
    })

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

    const resumePdfSchema = z.object({
        html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
    })

    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    })

    const jsonContent = JSON.parse(response.text)
    const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

    return pdfBuffer
}

module.exports = { generateInterviewReport, generateResumePdf }